Add `ffmpeg` support in nvproxy
google/gvisor pull request #11321
Opened 2024-12-23 23:19 UTC by 2022tgoel

2024-12-23 23:22 UTC, EtiennePerot commented
cc @ayushr2

2025-01-02 18:53 UTC, EtiennePerot commented on test/gpu/ffmpeg_test.go
> +	cmd := []string{"bash", "-c", "ffmpeg -i video.mp4 -c:v h264_nvenc -preset fast output.mp4 && ffmpeg -y -vsync 0 -c:v h264_cuvid -i output.mp4 video.mp4"}
Encoding and decoding should be two separate unit tests. (They can use the same image)

2025-01-02 18:54 UTC, EtiennePerot commented
Please notify here when this is ready for review (and after squashing all commits to one)

2025-01-02 21:42 UTC, 2022tgoel commented
Hi, the PR is ready for review. I have verified that `ffmpeg_test` is successful on T4, A10, and L4 gpus.

2025-01-03 02:30 UTC, EtiennePerot requested changes
Thanks for the work!
Please reword the commit message to be more descriptive, especially the first line which should explain that this commit adds GPU video encoding/decoding support to nvproxy. With the current commit message, it would show up as only saying "add cap" in the commit log.

2025-01-03 02:30 UTC, EtiennePerot commented on images/benchmarks/ffmpeg/Dockerfile
> +ADD https://samples.ffmpeg.org/A-codecs/Nelly_Moser/h264_NellyMoser.mp4 encoded.mp4
nit: please add a newline at end of file.

2025-01-03 02:30 UTC, EtiennePerot commented on pkg/sentry/devices/nvproxy/frontend.go
> +	busInfoBuf := make([]byte, ctrlParams.BusInfoListSize*nvgpu.CtrlXxxInfoSize)
There needs to be a cap on `BusInfoListSize` to avoid a DoS vector from OOMing the Sentry here. Also need to check that `busInfoBuf` is non-empty. The user controls the size of this buffer and currently if I read the code correctly the user can set a size of zero.

The host kernel driver must also be doing similar checks; please verify the upper and lower thresholds it uses, and use the same thresholds here.

2025-01-03 02:30 UTC, EtiennePerot commented on pkg/sentry/devices/nvproxy/frontend.go
> +
nit: remove blank line

2025-01-03 02:30 UTC, EtiennePerot commented on pkg/sentry/devices/nvproxy/version.go
> +							nvgpu.NV2080_CTRL_CMD_BUS_GET_INFO:                                     simpleDriverStruct("NV2080_CTRL_BUS_GET_INFO_PARAMS"), // TODO: Difference with V2 is alignment. Look into this.
Can you say more here? Perhaps there a way to merge this with the V2-handling code? Check out the `RmAllocParamType` which acts as a "superset type" for both `NVOS21_PARAMETERS` and `NVOS64_PARAMETERS` as inspiration. Can something similar be done here?

If not, the tests will complain about a "TODO" comment without an owner. In this case, can you replace this with `TODO(2022tgoel): ...`?

2025-01-03 19:37 UTC, EtiennePerot commented
Looks good to me now. cc @ayushr2 want to review too?

2025-01-03 19:37 UTC, EtiennePerot approved these changes

2025-01-04 18:52 UTC, ayushr2 commented on pkg/sentry/devices/nvproxy/version.go
> +					nvgpu.NVENC_SW_SESSION:           allocHandler(rmAllocSimple[nvgpu.NVA0BC_ALLOC_PARAMETERS], nvconf.CapVideo),
NVENC_SW_SESSION was only added in 550.40.07.

2025-01-04 18:52 UTC, ayushr2 commented on pkg/sentry/devices/nvproxy/version.go
> +					nvgpu.NVCDB0_VIDEO_DECODER:       allocHandler(rmAllocSimple[nvgpu.NV_BSP_ALLOCATION_PARAMETERS], nvconf.CapVideo),
NVCDB0_VIDEO_DECODER was only added in 560.28.03.

2025-01-04 18:52 UTC, ayushr2 commented on pkg/abi/nvgpu/ctrl.go
> +	NV0080_CTRL_CMD_GR_GET_CAPS_V2 = 0x801109
nit: NV0080_CTRL_CMD_GR_GET_CAPS_V2 should come after NV0080_CTRL_CMD_GR_GET_INFO since its value to greater. We try to keep these const blocks sorted.

2025-01-04 18:52 UTC, ayushr2 commented on pkg/abi/nvgpu/uvm.go
> +func (p *UVM_PAGEABLE_MEM_ACCESS_ON_GPU_PARAMS) GetStatus() uint32 {
Nit: All exported functions need to have a comment. Add:
// GetStatus implements HasStatus.GetStatus.

2025-01-08 08:58 UTC, ayushr2 approved these changes
Just nits. LGTM.

Thanks for your contribution, this is good work. Glad to see so many contributions from Modal.

P.S. please rebase to HEAD and resolve conflicts

2025-01-08 08:58 UTC, ayushr2 commented on pkg/sentry/devices/nvproxy/version.go
> +			abi.allocationClass[nvgpu.NVENC_SW_SESSION] = allocHandler(rmAllocSimple[nvgpu.NVA0BC_ALLOC_PARAMETERS], nvconf.CapVideo)
nit: move this to line 742, since all `controlCmd` changes are grouped together, this is currently breaking that grouping.

2025-01-08 08:58 UTC, ayushr2 commented on pkg/sentry/devices/nvproxy/version.go
> +		// The following exist on the "560" branch.
560.28.03 exists on the main branch: https://github.com/NVIDIA/open-gpu-kernel-modules/commit/448d5cc65624d3aa69015efa0d3fb50fd9729f41.

You can make the comment "560.28.03 is an intermediate unqualified version."
It should inherit from v555_42_02, which you have implemented correctly.

2025-01-08 14:38 UTC, 2022tgoel commented
I've rebased and fix the last few nits. Let me know if there's anything else!

2025-01-08 19:20 UTC, EtiennePerot commented on test/gpu/ffmpeg_test.go
> +	opts, err := dockerutil.GPURunOpts(dockerutil.SniffGPUOpts{Capabilities: "NVIDIA_DRIVER_CAPABILITIES=compute,video"})
Apologies for the sudden change, but 2edcee37d9fbe56b8385c42c171c689da02dbc41 changes the behavior of this field to no longer need to be prefixed by `NVIDIA_DRIVER_CAPABILITIES=`. So please remove this prefix here and in the other test below.

2025-01-08 19:36 UTC, 2022tgoel commented on test/gpu/ffmpeg_test.go
> +	opts, err := dockerutil.GPURunOpts(dockerutil.SniffGPUOpts{Capabilities: "NVIDIA_DRIVER_CAPABILITIES=compute,video"})
👍

2025-01-08 20:59 UTC, EtiennePerot approved these changes

2025-01-08 21:57 UTC, EtiennePerot commented
The tests ran and there are two failures:

```
Executing tests from //pkg/sentry/devices/nvproxy:nvproxy_test
-----------------------------------------------------------------------------
--- FAIL: TestFilterCapabilities (0.00s)
    --- FAIL: TestFilterCapabilities/compute,display,graphics,ngx,utility,video,compat32 (0.00s)
        nvproxy_test.go:320: uvmIoctlFilters("compute,display,graphics,ngx,utility,video,compat32") returned 30 UVM ioctls, expected 31
    --- FAIL: TestFilterCapabilities/compute,graphics,utility,video (0.00s)
        nvproxy_test.go:320: uvmIoctlFilters("compute,graphics,utility,video") returned 30 UVM ioctls, expected 31
    --- FAIL: TestFilterCapabilities/video (0.00s)
        nvproxy_test.go:320: uvmIoctlFilters("video") returned 2 UVM ioctls, expected 3
    --- FAIL: TestFilterCapabilities/utility,video (0.00s)
        nvproxy_test.go:320: uvmIoctlFilters("utility,video") returned 30 UVM ioctls, expected 31
```

and

```
Executing tests from //pkg/sentry/devices/nvproxy:nvproxy_driver_parity_test
-----------------------------------------------------------------------------
--- FAIL: TestSupportedStructNames (0.00s)
    --- FAIL: TestSupportedStructNames/550.54.15 (28.60s)
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_GR_GET_CAPS_PARAMS_V2" not found in parser output for version "550.54.15"
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_FIFO_GET_CAPS_PARAMS_V2" not found in parser output for version "550.54.15"
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_CMD_NVJPG_GET_CAPS_V2_PARAMS" not found in parser output for version "550.54.15"
    --- FAIL: TestSupportedStructNames/535.216.01 (29.27s)
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_GR_GET_CAPS_PARAMS_V2" not found in parser output for version "535.216.01"
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_CMD_NVJPG_GET_CAPS_V2_PARAMS" not found in parser output for version "535.216.01"
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_FIFO_GET_CAPS_PARAMS_V2" not found in parser output for version "535.216.01"
    --- FAIL: TestSupportedStructNames/535.183.06 (29.67s)
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_CMD_NVJPG_GET_CAPS_V2_PARAMS" not found in parser output for version "535.183.06"
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_GR_GET_CAPS_PARAMS_V2" not found in parser output for version "535.183.06"
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_FIFO_GET_CAPS_PARAMS_V2" not found in parser output for version "535.183.06"
    --- FAIL: TestSupportedStructNames/550.54.14 (30.43s)
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_GR_GET_CAPS_PARAMS_V2" not found in parser output for version "550.54.14"
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_CMD_NVJPG_GET_CAPS_V2_PARAMS" not found in parser output for version "550.54.14"
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_FIFO_GET_CAPS_PARAMS_V2" not found in parser output for version "550.54.14"
    --- FAIL: TestSupportedStructNames/560.35.03 (30.89s)
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_CMD_NVJPG_GET_CAPS_V2_PARAMS" not found in parser output for version "560.35.03"
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_GR_GET_CAPS_PARAMS_V2" not found in parser output for version "560.35.03"
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_FIFO_GET_CAPS_PARAMS_V2" not found in parser output for version "560.35.03"
    --- FAIL: TestSupportedStructNames/550.90.12 (31.28s)
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_GR_GET_CAPS_PARAMS_V2" not found in parser output for version "550.90.12"
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_CMD_NVJPG_GET_CAPS_V2_PARAMS" not found in parser output for version "550.90.12"
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_FIFO_GET_CAPS_PARAMS_V2" not found in parser output for version "550.90.12"
    --- FAIL: TestSupportedStructNames/550.90.07 (31.78s)
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_FIFO_GET_CAPS_PARAMS_V2" not found in parser output for version "550.90.07"
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_GR_GET_CAPS_PARAMS_V2" not found in parser output for version "550.90.07"
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_CMD_NVJPG_GET_CAPS_V2_PARAMS" not found in parser output for version "550.90.07"
    --- FAIL: TestSupportedStructNames/550.127.05 (31.79s)
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_GR_GET_CAPS_PARAMS_V2" not found in parser output for version "550.127.05"
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_FIFO_GET_CAPS_PARAMS_V2" not found in parser output for version "550.127.05"
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_CMD_NVJPG_GET_CAPS_V2_PARAMS" not found in parser output for version "550.127.05"
    --- FAIL: TestSupportedStructNames/535.183.01 (13.75s)
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_GR_GET_CAPS_PARAMS_V2" not found in parser output for version "535.183.01"
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_CMD_NVJPG_GET_CAPS_V2_PARAMS" not found in parser output for version "535.183.01"
        nvproxy_driver_parity_test.go:100: struct "NV0080_CTRL_FIFO_GET_CAPS_PARAMS_V2" not found in parser output for version "535.183.01"
--- FAIL: TestStructDefinitionParity (0.00s)
    --- FAIL: TestStructDefinitionParity/535.183.06 (13.83s)
        nvproxy_driver_parity_test.go:141: struct "NV0080_CTRL_FIFO_GET_CAPS_PARAMS_V2" not found in parser output for version "535.183.06"
        nvproxy_driver_parity_test.go:141: struct "NV0080_CTRL_CMD_NVJPG_GET_CAPS_V2_PARAMS" not found in parser output for version "535.183.06"
        nvproxy_driver_parity_test.go:141: struct "NV0080_CTRL_GR_GET_CAPS_PARAMS_V2" not found in parser output for version "535.183.06"
    --- FAIL: TestStructDefinitionParity/535.216.01 (13.84s)
        nvproxy_driver_parity_test.go:141: struct "NV0080_CTRL_FIFO_GET_CAPS_PARAMS_V2" not found in parser output for version "535.216.01"
        nvproxy_driver_parity_test.go:141: struct "NV0080_CTRL_CMD_NVJPG_GET_CAPS_V2_PARAMS" not found in parser output for version "535.216.01"
        nvproxy_driver_parity_test.go:141: struct "NV0080_CTRL_GR_GET_CAPS_PARAMS_V2" not found in parser output for version "535.216.01"
    --- FAIL: TestStructDefinitionParity/550.54.15 (14.50s)
        nvproxy_driver_parity_test.go:141: struct "NV0080_CTRL_FIFO_GET_CAPS_PARAMS_V2" not found in parser output for version "550.54.15"
        nvproxy_driver_parity_test.go:141: struct "NV0080_CTRL_GR_GET_CAPS_PARAMS_V2" not found in parser output for version "550.54.15"
        nvproxy_driver_parity_test.go:141: struct "NV0080_CTRL_CMD_NVJPG_GET_CAPS_V2_PARAMS" not found in parser output for version "550.54.15"
    --- FAIL: TestStructDefinitionParity/550.54.14 (14.62s)
        nvproxy_driver_parity_test.go:141: struct "NV0080_CTRL_CMD_NVJPG_GET_CAPS_V2_PARAMS" not found in parser output for version "550.54.14"
        nvproxy_driver_parity_test.go:141: struct "NV0080_CTRL_FIFO_GET_CAPS_PARAMS_V2" not found in parser output for version "550.54.14"
        nvproxy_driver_parity_test.go:141: struct "NV0080_CTRL_GR_GET_CAPS_PARAMS_V2" not found in parser output for version "550.54.14"
    --- FAIL: TestStructDefinitionParity/550.90.12 (14.82s)
        nvproxy_driver_parity_test.go:141: struct "NV0080_CTRL_FIFO_GET_CAPS_PARAMS_V2" not found in parser output for version "550.90.12"
        nvproxy_driver_parity_test.go:141: struct "NV0080_CTRL_GR_GET_CAPS_PARAMS_V2" not found in parser output for version "550.90.12"
        nvproxy_driver_parity_test.go:141: struct "NV0080_CTRL_CMD_NVJPG_GET_CAPS_V2_PARAMS" not found in parser output for version "550.90.12"
    --- FAIL: TestStructDefinitionParity/550.90.07 (14.94s)
         [...]

2025-01-09 14:05 UTC, 2022tgoel commented
Tests should pass now.

2025-01-09 17:38 UTC, ayushr2 approved these changes

2025-01-09 20:27 UTC, merged

2025-01-09 22:52 UTC, EtiennePerot commented
Thanks for contributing!

2025-01-10 02:31 UTC, ayushr2 commented
@2022tgoel I think TestFffmpegDecodeGPU and TestFffmpegEncodeGPU are failing now: https://buildkite.com/gvisor/release/builds/4200#01944cd9-e539-4698-bb43-0e624e68ad40