Add flag to disable container spec validation when restoring checkpoints
google/gvisor pull request #11323
Opened 2024-12-27 03:17 UTC by cweld510

This PR adds a new flag entitled `skip-restore-spec-validation-unsafe`, defaulting to false. If the flag is set, the container spec given when restoring a checkpoint will no longer be validated against the original container spec given when the checkpoint was taken. In practice, many spec differences are benign, and it can be useful to allow the container specs to vary somewhat between checkpoint and restore. See https://github.com/google/gvisor/issues/11307 .

2024-12-27 22:24 UTC, EtiennePerot commented
Please move the word "unsafe" to beginning of the flag/variable name (`--unsafe-skip-restore-spec-validation`); otherwise it kind of sounds like it is skipping something unsafe (which would be a safe thing to do).

2024-12-27 22:52 UTC, cweld510 commented
Thanks, done!

2024-12-28 00:58 UTC, EtiennePerot requested changes

2024-12-28 00:58 UTC, EtiennePerot commented on runsc/boot/restore.go
> +		return r.restore(l, info.conf.SkipRestoreSpecValidationUnsafe)
Still need to update this one.

2024-12-30 16:36 UTC, cweld510 commented on runsc/boot/restore.go
> +		return r.restore(l, info.conf.SkipRestoreSpecValidationUnsafe)
Fixed; really sorry about that.

2024-12-30 18:50 UTC, EtiennePerot approved these changes

2024-12-30 19:48 UTC, merged