Fix proc.(*fdDir).IterDirents for VFS2
google/gvisor pull request #3895
Opened 2020-09-10 13:49 UTC by btw616

Currently the returned offset is an index, and we can't
compare it with file descriptors. Instead, we can return
the next fd to serialize plus 2 (which accounts for "."
and "..") as the offset.

Fixes: #3894

2020-09-11 01:29 UTC, fvoznika reviewed
Thanks for the fix! Do you mind adding a test in test/syscalls/linux/proc.cc that covers this case?

2020-09-11 01:35 UTC, fvoznika requested changes
What's wrong with the function is the search. It should be comparing the index and not the FD value at the index:
`idx := sort.Search(len(fds), func(i int) bool { return int64(i) >= relOffset })`

2020-09-11 02:50 UTC, btw616 commented
> Thanks for the fix! Do you mind adding a test in test/syscalls/linux/proc.cc that covers this case?

Sure, no problem. :)

2020-09-11 02:57 UTC, btw616 commented
> What's wrong with the function is the search. It should be comparing the index and not the FD value at the index:
> `idx := sort.Search(len(fds), func(i int) bool { return int64(i) >= relOffset })`

Returning index as the offset can be problematic. Below is an example:

In the first `getdents()` call, assuming we have:

```
fds = [0, 1, 2, 9, 10]
       ^
       |
   relOffset = 0
```

And if only [0, 1, 2, 9] are returned by this call (due to the limit of
the buffer size provided by user), the returned offset will be 6 (4 + 2). 
And in the next call, the `relOffset` will be 4.

But if another FD is opened and its value is smaller than 9 (e.g. 5) before
the next `getdents()` call, then in the next `getdents()` call, we will have:

```
fds = [0, 1, 2, 5, 9, 10]
                   ^
                   |
               relOffset = 4
```

And 9 will be returned again.

2020-09-11 10:09 UTC, btw616 commented
https://github.com/google/gvisor/blob/365545855f7713236d77d3e263ad09ebffa85bb2/test/syscalls/linux/getdents.cc#L382

It looks above `TYPED_TEST(GetdentsTest, ProcSelfFd)` test can already catch the bug of using indexes to find the next FD to serialize (as it will open FDs first, iterate and close FDs through `/proc/self/fd`, and finally check whether all the reserved FDs are closed), so I only added a test to cover the case of comparing index and FD values.

2020-09-15 02:08 UTC, fvoznika requested changes
Just a few nits. Look good otherwise.

2020-09-15 02:08 UTC, fvoznika commented on test/syscalls/linux/proc.cc
> +static void CheckFdDirGetdentsDuplicates(std::string path) {
const std:string& path

2020-09-15 02:08 UTC, fvoznika commented on test/syscalls/linux/proc.cc
> +// This is a regression test for #3894
gvisor.dev/issues/3894

Here and below.

2020-09-15 02:08 UTC, fvoznika commented on test/syscalls/linux/proc.cc
> +TEST(ProcSelfFd, Issue3894GetdentsDuplicates) {
Let's name it just `GetdentsDuplicates` the comment already refers to the bug. It helps to keep test names easier to read and type.

2020-09-15 03:19 UTC, btw616 commented
> Just a few nits. Look good otherwise.

Thanks for the review!

2020-09-15 16:56 UTC, fvoznika approved these changes

2020-09-15 18:01 UTC, ayushr2 reviewed
Nit: could you also fix the comment on the `IterDirents` function to say "IterDirents implements kernfs.inodeDynamicLookup.IterDirents."

2020-09-15 19:12 UTC, merged

2020-09-16 05:50 UTC, btw616 commented
> Nit: could you also fix the comment on the `IterDirents` function to say "IterDirents implements kernfs.inodeDynamicLookup.IterDirents."

Sure. After a quick grepping, it looks there are some other comments not including the interface method name as well. This pull has been merged, I can send a new pull to fix this and other similar ones. Thanks!

2020-09-16 07:02 UTC, ayushr2 commented
> Sure. After a quick grepping, it looks there are some other comments not including the interface method name as well. This pull has been merged, I can send a new pull to fix this and other similar ones. Thanks!

@btw616 Thank you for your contributions!