Fix a couple of typos on performance.md
google/gvisor pull request #4018
Opened 2020-09-20 08:33 UTC by didier-durand

2 typos spotted in current version and fixed.
Best
Didier

2020-09-21 00:52 UTC, ianlewis requested changes

2020-09-21 00:52 UTC, ianlewis commented on g3doc/architecture_guide/performance.md
> +do minimal work per request, most like the `redis` case, they suffer from high
I think this should be 'much like the redis case'

2020-09-21 04:34 UTC, didier-durand commented
@ianlewis : Ian, fixed according to your proposal. Didier

2020-09-22 09:54 UTC, ianlewis approved these changes
LGTM

2020-09-24 22:33 UTC, merged