Add support for pause/restore in containerd shim
google/gvisor pull request #5237
Opened 2021-01-11 07:00 UTC by travigd

Happy to add tests if necessary (not sure where those would go at this point).

Tested by `ctr t pause` and `ctr t resume`-ing a container.

This seems to be necessary to implement checkpoint/restore for containerd (containerd calls pause before checkpointing, then resumes it -- even though that's not strictly necessary for gVisor).

2021-01-13 19:49 UTC, fvoznika requested changes
Thanks for the change. A few comments below.

2021-01-13 19:49 UTC, fvoznika commented on pkg/shim/runsc/runsc.go
> +	if _, err := cmdOutput(r.command(context, "pause", id), true); err != nil {
s/pause/resume

2021-01-13 19:49 UTC, fvoznika commented on pkg/shim/v2/service.go
> +	err := s.task.Runtime().Pause(ctx, r.ID)
Add check for s.task being nil:
```
if s.task == nil {
	log.L.Debugf("Pause error, id: %s: container not created", r.ID)
	return nil, errdefs.ToGRPCf(errdefs.ErrFailedPrecondition, "container must be created")
}
```

2021-01-13 19:49 UTC, fvoznika commented on pkg/shim/v2/service.go
> +	err := s.task.Runtime().Resume(ctx, r.ID)
Add check for s.task being nil.

2021-01-13 19:49 UTC, fvoznika commented on pkg/shim/runsc/runsc.go
> +		return fmt.Errorf("unable to pause: %s", err)
Let's use %w instead of %s to preserve the error.

2021-01-13 19:49 UTC, fvoznika commented on pkg/shim/runsc/runsc.go
> +		return fmt.Errorf("unable to resume: %s", err)
%w

2021-01-13 19:49 UTC, fvoznika commented on pkg/shim/v2/service.go
> +	return empty, err
Just being overzealous, return nil if `err != nil`.

2021-01-13 21:09 UTC, travigd commented
Thanks for the review comments, I believe I addressed all of them. Go is... not my strong suit... so the patience is appreciated. 😅🎉

2021-01-15 17:23 UTC, fvoznika approved these changes

2021-01-15 17:23 UTC, fvoznika commented
Looks great, thanks!

2021-01-15 17:40 UTC, avagin commented
@fvoznika @travigd do we need/can introduce a test for these commands?

2021-01-15 18:10 UTC, merged

2021-01-15 18:36 UTC, fvoznika commented
Ideally we would, but there are no tests for other commands and we need to build some infra to test them first.