vfs2/epoll: fix missing event trigger in epoll-in-epoll case
google/gvisor pull request #6428
Opened 2021-08-09 12:30 UTC by dillanzhou

In some cases, epoll fd would be registered in another epoll fd. Process
may call epoll_wait on the upper layer epoll fd, and the lower layer epoll
fd should generate EPOLLIN event if itself get any event.
But in VFS2, events generated for epoll fd could only be cleaned when
(*EpollInstance).ReadEvents is called. And this function is only called
when epoll_wait on the epoll fd. Therefore, when epoll_wait on the upper
layer epoll fd, the events generated in lower layer epoll fd would not
be cleaned even if it's not valid anymore, and lower layer epoll fd would
not report event to upper layer even if new event is triggered.

In this commit, (*EpollInstance).Readiness would also clean invalid events.
So, when epoll_wait on the upper layer epoll fd, Readiness function called
on lower layer epoll fd would clean invalid events. And lower layer could
report event to upper layer if new event is triggered.

A syscall test case is added to verify the commit.

Fixes https://github.com/google/gvisor/issues/6427

Signed-off-by: Jielong Zhou <jielong.zjl@antgroup.com>

2021-08-09 12:42 UTC, dillanzhou commented
> @googlebot I signed it!

2021-09-02 16:12 UTC, ayushr2 requested changes

2021-09-02 16:12 UTC, ayushr2 commented on test/syscalls/linux/epoll.cc
> +  int listen_fd = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
Create socket like this and capture in a `FileDescriptor` which would clean up after the scope ends.

https://cs.opensource.google/gvisor/gvisor/+/master:test/syscalls/linux/packet_socket_raw.cc;l=168-170;drc=dfb3273f887a80c25a6d133fd5a082153ba58570

2021-09-02 16:12 UTC, ayushr2 commented on test/syscalls/linux/epoll.cc
> +  listen(listen_fd, 1);
Assert that these syscalls succeed.

2021-09-02 16:12 UTC, ayushr2 commented on test/syscalls/linux/epoll.cc
> +  // first time
All comments should be proper sentences. Should start with capitalization and end with a period (full stop).

2021-09-02 16:12 UTC, ayushr2 commented on test/syscalls/linux/epoll.cc
> +  ASSERT_THAT(close(server_fd), SyscallSucceeds());
This is essentially the same as above, call this in a loop and explain why loop is of length 2.

2021-09-30 07:04 UTC, ayushr2 commented
Bumping this PR, can you please resolve the comments?

2021-10-01 23:22 UTC, tanjianfeng commented
> Bumping this PR, can you please resolve the comments?

Hi Ayush,

Thanks for review. Jielong's resigned from this position. I or someone in our team will cover him for this, but maybe one week later as we are taking holidays now.

2021-10-02 00:43 UTC, ayushr2 commented
@tanjianfeng Thanks for letting me know. I can take over this PR and get it reviewed.

2021-10-06 18:17 UTC, ayushr2 approved these changes
Approving so this can be pulled internally and I can fix the comments.

2021-10-11 16:49 UTC, merged