network: speed up createSocket() by giving protocal 0 in socket()
google/gvisor pull request #9283
Opened 2023-08-16 03:25 UTC by tianyuzhou95

In practice, we found that createSocket() could cost up to 40ms, which is an unacceptable overhead in FaaS(Function as a Service) scenario. The root cause is the bind() syscall runs into the slow path in kernel and invokes synchronize_net(), which is an expensive call.

From kernel commit[1] we learned that we could bypass this slow path by adjusting the socket() syscall before we call bind(). By giving the empty protocal number, the packet_create() will not call __register_prot_hook(), in which the kernel turn on the flag packet_sock.running. So when it comes to packet_do_bind(), it won't call synchronize_net() for there is no prot_hook to unregister.

Worst cost for bind() tested on Intel Xeon E5-2682 with Linux kernel 5.4 over 100 times:

  * before: 39633.274 us
  * after:     25.098 us

Reference:
[1] https://github.com/torvalds/linux/commit/902fefb82ef72a50c78cb4a20cc954b037a98d1c

2023-08-16 16:00 UTC, nlacasse requested changes

2023-08-17 02:06 UTC, tianyuzhou95 commented on runsc/sandbox/network.go
> +	fd, err := unix.Socket(unix.AF_PACKET, unix.SOCK_RAW, 0)
Thanks for pointing it out. I have added a simple comment at the end of the line.

2023-08-17 02:18 UTC, nlacasse commented on runsc/sandbox/network.go
> +	fd, err := unix.Socket(unix.AF_PACKET, unix.SOCK_RAW, 0)
Thanks

2023-08-17 02:18 UTC, nlacasse approved these changes

2023-08-17 17:33 UTC, merged