Fix EOF (^D) handling in devpts (partially addr #9333)
google/gvisor pull request #9336
Opened 2023-09-04 21:13 UTC by thundergolfer

This fixes the ctrl-d part of #9333.

Disclaimer: new to this codebase.

2023-09-04 22:10 UTC, nlacasse requested changes
Thanks for the fix, and the nice test. One minor nit.

2023-09-04 22:10 UTC, nlacasse commented on pkg/sentry/fsimpl/devpts/line_discipline.go
> +	} else {
Nit: `else` is not needed in this case, since the preceeding `if` block returns unconditionally.

2023-09-05 00:25 UTC, ayushr2 commented
Could you squash the two commits? Otherwise these will appear as two separate commits on the master branch after merge.

2023-09-05 00:27 UTC, thundergolfer commented
Oh sure, I thought I could squash just before merge. But I'll squash them now and force push.

2023-09-05 00:47 UTC, ayushr2 commented
We don't squash and merge from Github UI (unfortunately...). It needs be go through our internal system (via the "ready to pull" tag). [Copybara](https://github.com/google/copybara) will clone your PR as a new PR and merge that and close this. And in the process, it just pushes the commits from this branch onto master. So we request the commits are squashed (unless they are meant to be logically separated).

2023-09-05 01:01 UTC, thundergolfer commented
Make sense. Thanks for the explanation 👌

2023-09-05 16:06 UTC, nlacasse approved these changes

2023-09-05 19:39 UTC, nlacasse commented
This seems to break the `PtyTest.TermiosONLCR` test:
```
[ RUN      ] PtyTest.TermiosONLCR
test/syscalls/linux/pty.cc:466: Failure
Value of: ReadFd(fd.get(), &c, 1)
Expected: -1 (failure), with errno PosixError(errno=11 Resource temporarily unavailable)
  Actual: 0 (of type long)
[  FAILED  ] PtyTest.TermiosONLCR (5 ms)
```

Full logs [here](https://storage.googleapis.com/gvisor-buildkite/018a666d-8936-49f2-9f4e-076ab5c2df43/018a666d-d375-4eb9-a07f-be5ab3fa5e63/home/agent-090523-165034/.cache/bazel/_bazel_agent-090523-165034/99920da594400bd42ae3b33af614153e/execroot/__main__/bazel-out/k8-fastbuild/testlogs/test/syscalls/pty_test_runsc_ptrace_shared/shard_1_of_4/test.log)

2023-09-05 22:54 UTC, thundergolfer commented
Oh of course, this behavior is only valid in canonical mode, and that test disables that flag. Pushed a fix.

2023-09-05 23:15 UTC, nlacasse requested changes

2023-09-05 23:15 UTC, nlacasse commented on pkg/sentry/fsimpl/devpts/line_discipline.go
> +	if !pushed && l.termios.LEnabled(linux.ICANON) {
We have to hold `l.termiosMu` to access `l.termios`.

I would set `isCanon := t.ermios.LEnabled(linux.ICANON)`  while the lock is held on line 200, and then reference `isCanon` in this conditional.

2023-09-06 02:00 UTC, nlacasse approved these changes

2023-09-06 20:29 UTC, merged

2023-09-06 20:38 UTC, nlacasse commented
This is merged!  Thanks for the PR.